#!/bin/bash
zookeeper_pid_is_alive=
zookeeper_is_up=$(echo stat | nc localhost 2181)
while [[ -z $zookeeper_is_up ]]
do
  while [[ -z $zookeeper_is_alive ]]
  do
    KAFKA_OPTS="$KAFKA_OPTS -Dzookeeper.4lw.commands.whitelist=stat,dump" $KAFKA_PATH/bin/zookeeper-server-start.sh $KAFKA_PATH/config/zookeeper.properties &
    zookeeper_pid=$!
    sleep 1
    zookeeper_is_alive=$(ps cax | grep $zookeeper_pid)
  done
  sleep 5
  zookeeper_is_up=$(echo stat | nc localhost 2181)
done
kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
kafka_is_alive=
while [[ -z $kafka_is_up ]]
do
  while [[ -z $kafka_is_alive ]]
  do
    $KAFKA_PATH/bin/kafka-server-start.sh $KAFKA_PATH/config/server.properties &
    kafka_pid=$!
    sleep 1
    echo "Checking if pid $kafka_pid is alive"
    kafka_is_alive=$(ps cax | grep $kafka_pid)
    echo "$kafka_pid is alive: $kafka_is_alive"
  done
  sleep 5
  kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
done
